"""
CoderAgent - Generiert Production-Ready Code mit Claude API
und speichert strukturiert in AppFlowy Knowledge Base.

Setup:
    pip install anthropic crewai requests python-dotenv

Env vars (.env):
    ANTHROPIC_API_KEY=...
    APPFLOWY_BASE_URL=http://localhost:8000
    APPFLOWY_TOKEN=...
    APPFLOWY_WORKSPACE_ID=...
    APPFLOWY_DATABASE_ID=...
"""

import os
import json
import re
import sys
from datetime import date
from typing import Optional

import anthropic
import requests
from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Claude Client
# ---------------------------------------------------------------------------

_client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])


# ---------------------------------------------------------------------------
# AppFlowy API
# ---------------------------------------------------------------------------

class AppFlowySaver:
    def __init__(self):
        self.base_url = os.environ["APPFLOWY_BASE_URL"].rstrip("/")
        self.token = os.environ["APPFLOWY_TOKEN"]
        self.workspace_id = os.environ["APPFLOWY_WORKSPACE_ID"]
        self.database_id = os.environ["APPFLOWY_DATABASE_ID"]
        self.headers = {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json",
        }

    def search_existing(self, query: str) -> list[dict]:
        """Sucht in AppFlowy KB nach ähnlichem Code."""
        url = f"{self.base_url}/api/workspace/{self.workspace_id}/search"
        try:
            resp = requests.post(
                url,
                headers=self.headers,
                json={"query": query, "limit": 5},
                timeout=10,
            )
            resp.raise_for_status()
            return resp.json().get("data", [])
        except Exception as e:
            print(f"[AppFlowy] Search failed: {e}")
            return []

    def save_record(
        self,
        title: str,
        content: str,
        language: str,
        tags: list[str],
    ) -> Optional[str]:
        """Speichert Code-Record in AppFlowy Datenbank."""
        url = f"{self.base_url}/api/workspace/{self.workspace_id}/database/{self.database_id}/row"
        payload = {
            "data": {
                "Title": title,
                "Content": content,
                "Language": language,
                "Status": "Ready for Review",
                "GeneratedBy": "CoderAgent",
                "CreatedDate": str(date.today()),
                "Tags": ", ".join(tags),
            }
        }
        try:
            resp = requests.post(url, headers=self.headers, json=payload, timeout=15)
            resp.raise_for_status()
            row_id = resp.json().get("data", {}).get("id")
            print(f"[AppFlowy] Saved: {row_id}")
            return row_id
        except Exception as e:
            print(f"[AppFlowy] Save failed: {e}")
            return None


# ---------------------------------------------------------------------------
# Markdown Template
# ---------------------------------------------------------------------------

def wrap_in_template(
    feature_name: str,
    language: str,
    code: str,
    explanation: str,
    dependencies: list[str],
    usage_example: str,
    integration_points: list[str],
) -> str:
    dep_list = "\n".join(f"- {d}" for d in dependencies) if dependencies else "- (keine)"
    int_list = "\n".join(f"- {p}" for p in integration_points) if integration_points else "- (keine)"

    return f"""# {feature_name}
**Status:** Generated by CoderAgent
**Date:** {date.today()}
**Language:** {language}

## Description
{explanation}

## Installation
```bash
{_install_command(language, dependencies)}
```

## Usage
```{language.lower()}
{usage_example}
```

## Full Code
```{language.lower()}
{code}
```

## Dependencies
{dep_list}

## Integration Points
{int_list}

---
*Generated with Claude claude-opus-4-6 | CoderAgent v1.0*
"""


def _install_command(language: str, deps: list[str]) -> str:
    if not deps:
        return "# Keine externen Abhängigkeiten"
    lang = language.lower()
    if lang in ("javascript", "typescript", "react", "node"):
        return "npm install " + " ".join(deps)
    if lang == "python":
        return "pip install " + " ".join(deps)
    return "# Install: " + ", ".join(deps)


# ---------------------------------------------------------------------------
# Claude Code Generation
# ---------------------------------------------------------------------------

def generate_code_with_claude(
    requirement: str,
    language: str,
    existing_context: str = "",
) -> dict:
    """
    Nutzt Claude claude-opus-4-6 mit adaptive thinking für Code-Generierung.
    Gibt dict zurück: {code, explanation, dependencies, usage_example, integration_points}
    """
    context_block = (
        f"\n\nBestehender ähnlicher Code in unserer KB:\n{existing_context}"
        if existing_context
        else ""
    )

    system = f"""Du bist ein Senior Software-Engineer in unserem Team.
Stack: Node.js, React, Python, CrewAI, AppFlowy.
Schreib production-ready, gut kommentierten Code.{context_block}

Antworte IMMER als valides JSON mit diesen Keys:
{{
  "code": "<vollständiger Code als String>",
  "explanation": "<Was macht dieser Code? 2-3 Sätze>",
  "dependencies": ["dep1", "dep2"],
  "usage_example": "<kurzes Beispiel wie man den Code nutzt>",
  "integration_points": ["Wo wird das eingebaut?", "Welche Agents nutzen das?"]
}}"""

    prompt = f"""Schreib production-ready {language} Code für folgende Anforderung:

{requirement}

Anforderungen:
- Vollständiger, funktionierender Code mit deutschen Kommentaren
- Error-Handling
- TypeScript-Types wenn relevant
- Kein Placeholder-Code"""

    print(f"[Claude] Generiere {language}-Code...")

    # Streaming + adaptive thinking für komplexe Aufgaben
    with _client.messages.stream(
        model="claude-opus-4-6",
        max_tokens=8096,
        thinking={"type": "adaptive"},
        system=system,
        messages=[{"role": "user", "content": prompt}],
    ) as stream:
        response = stream.get_final_message()

    raw = ""
    for block in response.content:
        if block.type == "text":
            raw = block.text
            break

    # JSON aus Response extrahieren (auch wenn in Markdown-Block gewrappt)
    json_match = re.search(r"```json\s*([\s\S]*?)```", raw)
    if json_match:
        raw = json_match.group(1).strip()

    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # Fallback: Code direkt nutzen
        return {
            "code": raw,
            "explanation": f"Generierter {language} Code für: {requirement}",
            "dependencies": [],
            "usage_example": "// Siehe Full Code oben",
            "integration_points": ["Manuell zu integrieren"],
        }


# ---------------------------------------------------------------------------
# CoderAgent (Haupt-Interface)
# ---------------------------------------------------------------------------

class CoderAgent:
    def __init__(self):
        self.appflowy = AppFlowySaver()

    def generate(
        self,
        requirement: str,
        language: str = "JavaScript",
    ) -> dict:
        """
        Hauptfunktion: Requirement → Code → AppFlowy

        Returns:
            {
                "markdown": "...",
                "appflowy_id": "row_id oder None",
                "status": "success|error",
                "title": "..."
            }
        """
        print(f"\n{'='*60}")
        print(f"[CoderAgent] Starte: {requirement[:60]}...")
        print(f"[CoderAgent] Sprache: {language}")

        # 1. KB durchsuchen – existiert ähnliches?
        print("[CoderAgent] Durchsuche AppFlowy KB...")
        existing = self.appflowy.search_existing(requirement)
        existing_context = ""
        if existing:
            print(f"[CoderAgent] {len(existing)} ähnliche Einträge gefunden – nutze als Kontext")
            existing_context = "\n---\n".join(
                r.get("content", "")[:500] for r in existing[:2]
            )
        else:
            print("[CoderAgent] Kein ähnlicher Code – generiere neu")

        # 2. Code generieren
        result = generate_code_with_claude(requirement, language, existing_context)

        # 3. Markdown-Template erstellen
        feature_name = requirement.strip().capitalize()
        markdown = wrap_in_template(
            feature_name=feature_name,
            language=language,
            code=result["code"],
            explanation=result["explanation"],
            dependencies=result.get("dependencies", []),
            usage_example=result.get("usage_example", ""),
            integration_points=result.get("integration_points", []),
        )

        # 4. In AppFlowy speichern
        print("[CoderAgent] Speichere in AppFlowy...")
        row_id = self.appflowy.save_record(
            title=feature_name,
            content=markdown,
            language=language,
            tags=["#generated", "#code", f"#{language.lower()}"],
        )

        print(f"[CoderAgent] ✓ Fertig! AppFlowy ID: {row_id}")
        print("=" * 60)

        return {
            "markdown": markdown,
            "appflowy_id": row_id,
            "status": "success",
            "title": feature_name,
            "language": language,
        }


# ---------------------------------------------------------------------------
# CrewAI Integration (optional, falls CrewAI installiert)
# ---------------------------------------------------------------------------

def build_crewai_agent():
    """Erstellt einen CrewAI-Agent-Wrapper um CoderAgent."""
    try:
        from crewai import Agent, Task, Crew
        from crewai.tools import BaseTool
        from pydantic import BaseModel, Field

        coder = CoderAgent()

        class GenerateCodeInput(BaseModel):
            requirement: str = Field(description="Was soll programmiert werden?")
            language: str = Field(default="JavaScript", description="Programmiersprache")

        class GenerateCodeTool(BaseTool):
            name: str = "generate_code"
            description: str = (
                "Generiert Production-Ready Code basierend auf einer Anforderung "
                "und speichert ihn in AppFlowy."
            )
            args_schema: type[BaseModel] = GenerateCodeInput

            def _run(self, requirement: str, language: str = "JavaScript") -> str:
                result = coder.generate(requirement, language)
                return result["markdown"]

        agent = Agent(
            role="Code Generator",
            goal="Schreibe production-ready Code und speichere ihn strukturiert in AppFlowy",
            backstory=(
                "Erfahrener Software-Engineer, der Anforderungen in funktionierenden "
                "Code umwandelt und Wissen strukturiert in der KB ablegt."
            ),
            tools=[GenerateCodeTool()],
            verbose=True,
        )
        return agent

    except ImportError:
        print("[CrewAI] Nicht installiert – nutze CoderAgent direkt")
        return None


# ---------------------------------------------------------------------------
# CLI-Einstiegspunkt
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    requirement = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else "Erstelle AppFlowy API Bridge für Agents"
    language = os.environ.get("CODER_LANGUAGE", "JavaScript")

    agent = CoderAgent()
    result = agent.generate(requirement, language)

    print("\n--- MARKDOWN PREVIEW ---")
    print(result["markdown"][:800] + "...")
    print(f"\nAppFlowy ID: {result['appflowy_id']}")
    print("Status: Ready for Review")
