services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    volumes:
      - uptime_kuma_data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.rule=Host(`status.automation-plus-ki.de`)
      - traefik.http.routers.uptime-kuma.entrypoints=https
      - traefik.http.routers.uptime-kuma.tls.certresolver=letsencrypt
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
    networks:
      - coolify

volumes:
  uptime_kuma_data:
    external: true

networks:
  coolify:
    external: true
