apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ project_name | default('chatbot') }}-config
  namespace: {{ project_name | default('chatbot') }}
data:
  project_name: {{ project_name | default('chatbot') }}
  environment: {{ environment | default('dev') }}
