apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ project_name | default('chatbot') }}-pvc"
  namespace: "{{ project_name | default('chatbot') }}"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
